### ISSUE TITLE
Cross Teaching results

### ISSUE THREAD

**Issue by nhtsymh** [chy-upc/ABD#10]
Dear Author,

Hello, I have run python ./code/train_ACDC_Cross_Teaching.py and python ./code/test_ACDC.py, and I have obtained the results for model1 and model2. Could you please guide me on how to combine these two results to obtain the Cross Teaching results as presented in your paper? I would greatly appreciate your assistance.

Thank you very much.

Best regards.

**Comment by nhtsymh** [comment]
Additionally, could you tell me where I can find the related images from Figure 3?

**Comment by chy-upc** [comment]
> Dear Author,
> 
> Hello, I have run python ./code/train_ACDC_Cross_Teaching.py and python ./code/test_ACDC.py, and I have obtained the results for model1 and model2. Could you please guide me on how to combine these two results to obtain the Cross Teaching results as presented in your paper? I would greatly appreciate your assistance.
> 
> Thank you very much.
> 
> Best regards.

The results presented in the paper reflect the performance of Model 1. We found that the UNet (Model 1) is more stable than the Swin-UNet (Model 2) during the training process. Have a nice day!

**Comment by chy-upc** [comment]
> Additionally, could you tell me where I can find the related images from Figure 3?

First, you need to read a 2D slice image. Then, input the image into the model to obtain a mask. Finally, assign the corresponding colors based on the mask values. Best regards.

**Comment by nhtsymh** [comment]
> > 此外，您能否告诉我在哪里可以找到图 3 中的相关图像？
> 
> 首先，您需要读取 2D 切片图像。然后，将图像输入到模型中以获得蒙版。最后，根据蒙版值分配相应的颜色。此致敬意。

Thanks for your help.
