### ISSUE TITLE
ACDC Dataset

### ISSUE THREAD

**Issue by hoagthien** [chy-upc/ABD#5]
I couldn't know how to get the processed ACDC dataset. 
Could you push it on the drive suitable for international researcher to seek. Pls

**Comment by chy-upc** [comment]
You can refer to the website at [ACDC](https://github.com/HiLab-git/SSL4MIS/tree/master/data/ACDC), the inside is processed ACDC data set. Direct download is available.

**Comment by hoagthien** [comment]
Thanks for your advice
