### ISSUE TITLE
Questions about PROMISE12 preprocessing

### ISSUE THREAD

**Issue by BinYCn** [chy-upc/ABD#9]
I downloaded the PROMISE12 dataset based on the readme, but there is no preprocessing code, can you provide it please?

**Comment by bigfishfour** [comment]
> I downloaded the PROMISE12 dataset based on the readme, but there is no preprocessing code, can you provide it please?

hello，do you solve this problem?

**Comment by chy-upc** [comment]
The code for processing the PROMISE12 dataset is executed during the run of train_PROMISE12.py. For details, you can refer to the **class Promise12(Dataset):**  in ./code/dataloaders/promise12.py.
